repos:
  - repo: local
    hooks:
    - id: pyupgrade
      name: pyupgrade
      language: python
      types: [python]
      entry: poetry run pyupgrade

    - id: fmt
      name: fmt
      language: python
      types: [python]
      entry: poetry run black
