plugins = [
    "system",
    "system_groups",
    "system_users",
    "aliases",
    "rules",
    "interfaces",
    "gateways",
    "unbound",
    "installed_packages",
    "haproxy",
    "openvpn_servers",
]
