plugins = [
    # Standard, in alphabetical order.
    "aliases",
    "ca",
    "cert",
    "cron",
    "dhcpd",
    "dhcpdv6",
    "diag",
    "dnshaper",
    "filter",
    "gateways",
    "hasync",
    "ifgroups",
    "installedpackages",
    "interfaces",
    "ipsec",
    "nat",
    "notifications",
    "ntpd",
    "openvpn",
    "ovpnserver",
    "ppps",
    "proxyarp",
    "rrd",
    "snmpd",
    "shaper",
    "sshdata",
    "staticroutes",
    "switches",
    "sysctl",
    "syslog",
    "system_groups",
    "system_users",
    "system",
    "unbound",
    "virtualip",
    "vlans",
    "widgets",
    "wizardtemp",
    "wol",

    # Installed packages, in alphabetical order.
    "installed_haproxy",
    "installed_lightsquid",
    "installed_menu",
    "installed_service",
    "installed_servicewatchdog",
    "installed_zabbixagentlts",

]
