plugins = [
    # Standard, in alphabetical order.
    "aliases",
    "ca",
    "filter_rules",
    "gateways",
    "hasync",
    "ifgroups",
    "installed_packages",
    "interfaces",
    "ipsec",
    "notifications",
    "ntpd",
    "openvpn_servers",
    "rrd",
    "sshdata",
    "staticroutes",
    "sysctl",
    "syslog",
    "system_groups",
    "system_users",
    "system",
    "unbound",
    "virtualip",
    "widgets",
    "wol",

    # Installed packages, in alphabetical order.
    "cron",
    "haproxy",

]
