plugins = [
    # Show what isn't and is processed.
    "report_unknown_installedpackages",
    "installedpackages_list",

    # Standard, in alphabetical order.
    "aliases",
    "ca",
    "cert",
    "cron",
    "dhcpd",
    "dhcpdv6",
    "diag",
    "dnshaper",
    "filter",
    "gateways",
    "hasync",
    "ifgroups",
    "installedpackages",
    "interfaces",
    "ipsec",
    "nat",
    "notifications",
    "ntpd",
    "openvpn",
    "ovpnserver",
    "ppps",
    "proxyarp",
    "rrd",
    "snmpd",
    "shaper",
    "sshdata",
    "staticroutes",
    "switches",
    "sysctl",
    "syslog",
    "system_groups",
    "system_users",
    "system",
    "unbound",
    "virtualip",
    "vlans",
    "widgets",
    "wizardtemp",
    "wol",

    # Installed packages, in alphabetical order.
    "installed_freeradius",
    "installed_freeradiuseapconf",
    "installed_freeradiusclients",
    "installed_freeradiusinterfaces",
    "installed_haproxy",
    "installed_lightsquid",
    "installed_menu",
    "installed_pfblockerng",
    "installed_pfblockerngdnsbl",
    "installed_pfblockernglistsv4",
    "installed_pfblockerngtopspammers",
    "installed_service",
    "installed_servicewatchdog",
    "installed_squid",
    "installed_squidantivirus",
    "installed_squidauth",
    "installed_squidcache",
    "installed_squidguardacl",
    "installed_squidguarddefault",
    "installed_squidguarddest",
    "installed_squidguardgeneral",
    "installed_squidguardrewrite",
    "installed_squidguardtime",
    "installed_squidnac",
    "installed_squidremote",
    "installed_squidreversegeneral",
    "installed_squidreversepeer",
    "installed_squidreverseuri",
    "installed_squidsync",
    "installed_squidtraffic",
    "installed_squidusers",
    "installed_suricata",
    "installed_suricata_rule",
    "installed_suricata_sid_mgmt_lists",
    "installed_suricatasync",
    "installed_vpn_openvpn_export",
    "installed_zabbixagentlts",

]
