plugins = [
    "system",
    "system_groups",
    "system_users",
    "aliases",
    "filter_rules",
    "interfaces",
    "ifgroups",
    "gateways",
    "virtualip",
    "unbound",
    "hasync",
    "ntpd",
    "sysctl",
    "ca",
    "notifications",
    "sshdata",
    "installed_packages",
    "haproxy",
    "ipsec",
    "openvpn_servers",
]
